# -*- coding: utf-8 -*-
"""python project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNykC-wUshU8dKDQDu-BgaK6pb8pzXcL
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
#load the dataset
df = pd.read_csv("/content/Student_Academic_Stress.csv")

df.keys()

df.values

df.columns

target=df['Aca_stress_rate']
target

#preparing dataset
dataset=pd.DataFrame(df.values,columns=df.columns)
dataset

dataset['mental_health']=target
dataset

dataset.info()

#summerizing tha statistics of data
dataset.describe()

#check the missing values
dataset.isnull().sum()

#Exploratory data analysis
#Correlation
dataset.corr()

import seaborn as sns
sns.pairplot(dataset)

#Independent and dependent feature
x=dataset.iloc[:,:-6]
y=dataset.iloc[:,-6]
x = dataset[['Aca_stage','Peer_press','Aca_press_home',
             'Study_environment','Coping_strategy',
             'bad_habits','Aca_comp_rate']]
x.head()

y=dataset['Aca_stress_rate']

#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
x_train

##standardizing the dataset
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x_train=scaler.fit_transform(x_train)

x_test=scaler.transform(x_test)

x_train

from sklearn.linear_model import LinearRegression

regression=LinearRegression()

regression.fit(x_train,y_train)

print(regression.coef_)

print(regression.intercept_)

regression.get_params()

#prediction with testing
reg_pred=regression.predict(x_test)

reg_pred

#plot scatter plot for the prediction
plt.scatter(y_test,reg_pred)

#residuals(error)
residual=y_test-reg_pred

residual

sns.displot(residual,kind="kde")

#scatter plot with respect to prediction
plt.scatter(reg_pred,residual)

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(y_test,reg_pred))
print(mean_squared_error(y_test,reg_pred))
print(np.sqrt(mean_squared_error(y_test,reg_pred)))

#R square and adjusted Rsquare
from sklearn.metrics import r2_score
score=r2_score(y_test,reg_pred)
print(score)

#displaying adjusted r square
1-(1-score)*(len(y_test)-1)/(len(y_test)-x_test.shape[1]-1)

df.values[0].reshape(1,-1)

X_sample = df[['Aca_stage','Peer_press','Aca_press_home',
               'Study_environment','Coping_strategy',
               'bad_habits','Aca_comp_rate']].iloc[0]

X_sample = scaler.transform([X_sample])
prediction = regression.predict(X_sample)

print(prediction)

#Pickling the model file for development
import pickle
pickle.dump(regression,open("regmodel.pkl",'wb'))

pickled_model=pickle.load(open('regmodel.pkl','rb'))

#prediction
pickled_model.predict(X_sample)

